<!DOCTYPE html>
<html lang="pl">
<head>
	<meta charset="UTF-8">
	<meta name="Author" Content="Edvin Dulko">
	<link rel="stylesheet" href="<?= "$base_url/layout/index.css" ?>">
    <?php if(file_exists(__DIR__ . "/../pages/$page/index.css"))
        echo "<link rel='stylesheet' href='$base_url/pages/$page/index.css'>";
        if(isset($extra_styles)) foreach ($extra_styles as $href)
            echo "<link rel='stylesheet' href='$href'>";
    ?>
	<title><?= $title ?></title>
</head>
<body>
<header>
    <div class="header-coa">
        <img src="<?= "$base_url/layout/kvietka_herb.jpg" ?>">
    </div>
    <img class="header-main-img" src="<?= "$base_url/layout/nastup_header.jpg" ?>">
</header>
<main>
	<nav>
		<ul>
            <?php foreach ($nav_links as $path => $label) {
                $active = $page === $path
                    ? "class='active'" : "";
                echo "<li><a href='$base_url/$path' $active>$label</a></li>";
            } ?>
		</ul>
	</nav>
	<article class="root">
		<?= $page_content ?>
	</article>
</main>
<footer>
	by Edvin Dulko
</footer>
</body>
</html>