<?php $title = "O mnie" ?>

<h1>Moje zainteresowania</h1>

<div class="item">
    <h2 class="title nastup">‡NASTUP‡</h2>
    <div class="content">
        <div class="cont">
            <img height="320px" src="pages/home/nastup1.gif">
            <img height="320px" src="pages/home/latuska.jpg">
            <img height="320px" src="pages/home/nastup2.gif">
        </div>
        Złóż <a href="form">wniosek</a> by zostać <span class="nastup">NASTUP</span>oŭcam
        <div class="cont">
            <img height="500px" src="pages/home/nastup1.jpg">
            <img height="500px" src="pages/home/nastup_mom.jpg">
        </div>
        ‡Добрай раніцы мы з <span class="nastup">‡NASTUP‡</span>😎 <br>
        🙋🏻‍♂️Ф.В Кушаль⚡️БКА ЦБР 🌞 <br>
        👀Пранак еш іх 😋🍔 <br>
        🔥 Магілёў тупы горад🖕🖕 <br>
        👴🏻🥰Бацька наш Пазняк ✌️🎈 <br>
        💥Белы Легіён, Правы реванш👊 <br>
        🤮Смачна і кропка 🍟 <br>
        🔥СМАЛАНДІЯ 🔴🟠🔴😱 <br>
        😁 А Я ВАМ ЗАРАЗ ПАКАЖУ АДКУЛЬ ПЛАНАВАЎСЯ <span class="nastup">‡NASTUP‡</span>😎
    </div>
</div>

<hr>

<div class="item">
    <h2 class="title nastup">Kvietki</h2>
    <div class="content">
        Po-prostu kwiaty
        <div class="cont">
            <img height="500px" src="pages/home/kvietka1.jpg">
            <img height="500px" src="pages/home/kvietka2.jpg">
        </div>
        Główny kwiatuszek - <span class="nastup">Kviatłana Tulipanowska</span>
        <div class="cont">
            <img height="500px" src="pages/home/Tulipanowska1.jpg">
            <img height="500px" src="pages/home/Tulipanowska.gif">
            <img height="500px" src="pages/home/Tulipanowska2.jpg">
        </div>
        Herb <span class="nastup">kvietkaŭ</span>
        <div class="cont">
            <img height="500px" src="layout/kvietka_herb.jpg">
        </div>
    </div>
</div>

<hr>

<div class="item">
    <h2 class="title nastup">BKA BCR F.V.Kušal</h2>
    <div class="content">
        <div class="cont">
            <img height="500px" src="https://upload.wikimedia.org/wikipedia/be/2/28/Franci%C5%A1ak_Ku%C5%A1a%C4%BA.jpeg">
            <img height="500px" src="pages/home/nastup2.jpg">
            <img height="500px" src="https://upload.wikimedia.org/wikipedia/commons/0/04/Seal_of_Belarusian_Central_Council.svg">
        </div>
        Franciszek Wincentowicz Kuszel – białoruski działacz wojskowy i polityczny,
        oficer kontraktowy Wojska Polskiego, oficer Wojska Rosyjskiego,
        komendant mińskiej policji pomocniczej, szef sztabu Białoruskiej Samoobrony,
        działacz Białoruskiej Samopomocy Ludowej i Białoruskiej Centralnej Rady (BCR),
        komendant Białoruskiej Obrony Krajowej (BKA)
        <div class="cont">
            <img height="500px" src="pages/home/kusal1.jpg">
            <img height="500px" src="pages/home/kusal2.jpg">
        </div>
        <div class="cont">
            <img height="500px" src="pages/home/kusal3.jpg">
            <img height="500px" src="pages/home/kusal4.jpg">
        </div>
    </div>
</div>

<hr>

<div class="item">
    <h2 class="title nastup">Jabałctva</h2>
    <div class="content">
        <div class="cont">
            <img height="500px" src="pages/home/jabalt1.jpg">
            <img height="500px" src="pages/home/jabalt2.jpg">
        </div>
    </div>
</div>

<hr>

<div class="item">
    <h2 class="title">Programowanie</h2>
    <div class="content">
        <div class="cont">
            <img src="https://pbs.twimg.com/media/EdXAwNXWoAA_tgd.jpg">
        </div>
        Lubię programować w językach JavaScript, TypeScript i PHP
        <div class="cont">
            <img height="200px" src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Unofficial_JavaScript_logo_2.svg/800px-Unofficial_JavaScript_logo_2.svg.png">
            <img height="200px" src="https://miro.medium.com/max/1400/1*xdo0UBpyszvD7-7EH4TkIA.png">
            <img height="200px" src="https://www.tutorialsteacher.com/Content/images/home/typescript.svg">
            <img height="200px" src="https://www.php.net/images/meta-image.png">
        </div>
        I trochę umiem w C++
        <div class="cont">
            <img height="200px" src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/ISO_C%2B%2B_Logo.svg/800px-ISO_C%2B%2B_Logo.svg.png">
        </div>
        Mam
        <a href="https://github.com/GooseOb">github</a>
        i
        <a href="https://greasyfork.org/en/users/901750-gooseob">greasyfork</a>
    </div>
</div>