<?php $title="Wyszukiwanie grantów";
include __DIR__ . "/../../db_connect.php";

if(isset($_POST['submit'])):
	extract($_POST, EXTR_OVERWRITE, "form_");
	$result = mysqli_query($conn, "SELECT * FROM grants WHERE $key = '$value';");
?>
<div class='result'>
<?php
    if (mysqli_num_rows($result) == 0) {
	    echo "nie znaleziono <br>";
    } else {
        echo '<h1>Granty</h1>';
        include __DIR__ . '/../base/table.php';
    }
?>
<a href='searchbase'>do wyszukiwania</a>
<br>
<a href="base">do bazy</a>
</div>

<?php else: include __DIR__ . '/../../fields.php' ?>

<form method="POST" class="standard-box">
    <div class="title">
        Wyszukiwanie grantów
    </div>
    <div class="content">
        <label for='key'>Columna</label>
        <select id="key" name="key">
            <?php foreach($fields as $key => $label)
                echo "<option value='$key'>$label</option>";
            ?>
        </select>
        <label for='value'>Wartość</label>
        <input type="text" id="value" name="value">
    </div>
    <input type="submit" name="submit" value="Szukaj">
</form>

<?php endif; ?>